### ISSUE TITLE
g1t.gz error after compress.

### ISSUE THREAD

**Issue by JokerDKha** [three-houses-research-team/THAT#1]
Sorry for bother you, but i need help about this g1t.gz.
After decompress and edited file font picture, i try to compress it back to gz but it make a games freeze.
Sample file on Patch 4:
[font00_JPN.g1t.gz](https://github.com/three-houses-research-team/THAT/files/7554655/font00_JPN.g1t.gz)

**Comment by VelouriasMoon** [comment]
Could you walk me through your process? there's many steps along the way that can cause this including how you're trying to load the file in game.

**Comment by JokerDKha** [comment]
Step 1: I decompress g1t.gz to g1t
Step 2: I extract g1t to png with a G1Tool
Step 3: After edit png file, im use G1Tool to Replace new .dds  DXT5 to g1t
Step 4: I using THAT to compress g1t to gz again.
----------------------------------------------------------------------------------
I also try decompress and compress file not edit anything, but it still not working.
im using info path like patch 4 file:
010055D009F78000\romfs\patch4\nx\ui\font

**Comment by JokerDKha** [comment]
Update: i know what wrong with this file after compressing.
Original file have: some hex below a like this
![image](https://user-images.githubusercontent.com/56380626/142514064-6bf243d2-dc35-4d5c-aea6-3b661d210439.png)
In new file compress i copy that hex like original
![image](https://user-images.githubusercontent.com/56380626/142514177-70ac21d8-455c-4f84-9908-f4a4a77a852b.png)
and the game is working normal:
![image](https://user-images.githubusercontent.com/56380626/142514323-5695bf26-9a4b-405a-a022-86c8bff369c6.png)
Now i will edit picture again and compress it one more time, i will update soon if have any error.

**Comment by VelouriasMoon** [comment]
hmm, interesting find, guess it wouldn't be a Koei Tecmo game without useless padding that makes the game crash without it.
I'll have look into if there's any reason it exist.

**Comment by VelouriasMoon** [comment]
Issue was with the compression aligning the entries to 128 but not the end of the file, thus causes the issue of the missing bytes.

**Comment by JokerDKha** [comment]
Now i want mod this file. but File Found with no ID: rom:mods/nx/ui/font/72.bin.gz
What can i do now to mods this file?
this file location in data0.bin
![image](https://user-images.githubusercontent.com/56380626/142565883-49b91883-296c-4131-adce-cba2e73625d4.png)
@VelouriasMoon 
![image](https://user-images.githubusercontent.com/56380626/142565504-8867db04-5189-472c-9e16-d6da8b98544c.png)
